# Generated by Django 3.2.9 on 2023-04-08 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_reviews',
            name='feedback_update_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
