# Generated by Django 3.2.9 on 2023-04-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230408_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
