# Generated by Django 4.2 on 2023-05-15 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_project_user"),
        ("app", "0006_project_project_image"),
    ]

    operations = []
