# Generated by Django 4.2 on 2023-05-16 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_merge_0002_project_user_0006_project_project_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="user",
        ),
        migrations.AlterField(
            model_name="project",
            name="project_category_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.project_category"
            ),
        ),
    ]
