# Generated by Django 4.2 on 2023-05-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_project_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project_reviews",
            name="stars",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
